[clld]
menuitems_list = contributions parameters languages contributors sentences sources
app_template = afbo.mako
github_repos = clld/afbo
github_repos_data = cldf-datasets/afbo
sitemaps = parameter language
zenodo_concept_doi = 10.5281/zenodo.3610154
#zenodo_version_doi =
#zenodo_version_tag = v2026
dataset_github_repos = cldf-datasets/afbo
pacific_centered_maps = true

[mako]
directories_list = afbo:templates clldmpg:templates clld:web/templates
